name = "napy"
main = "index.ts"
compatibility_date = "2026-01-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./site/"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true