name = "napl-site"
main = "index.ts"
compatibility_date = "2026-01-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./example/"
binding = "ASSETS"

[observability]
[observability.logs]
enabled = true
invocation_logs = true