name = "napl-site"
main = "index.ts"
compatibility_date = "2026-01-19"

[assets]
directory = "./example/dist"
binding = "ASSETS"

[observability]
[observability.logs]
enabled = true
invocation_logs = true